export const BOOK_GENRES = [
  "Ficción",
  "No ficción",
  "Romance",
  "Misterio",
  "Thriller",
  "Ciencia ficción",
  "Fantasía",
  "Horror",
  "Aventura",
  "Histórica",
  "Biografía",
  "Autobiografía",
  "Poesía",
  "Drama",
  "Comedia",
  "Juvenil",
  "Infantil",
  "Autoayuda",
  "Negocios",
  "Cocina",
  "Arte",
  "Viajes",
  "Religión",
  "Filosofía",
  "Ciencia",
  "Tecnología",
  "Política",
  "Historia",
  "Psicología",
  "Sociología",
  "Educación",
  "Deportes",
  "Música",
  "Cine",
  "Cómics",
  "Manga",
  "Literatura clásica",
  "Literatura contemporánea",
  "Distopía",
  "Realismo mágico",
] as const;

export type BookGenre = typeof BOOK_GENRES[number];
