export const BOOK_GENRES = [
  "Ficción",
  "No ficción",
  "Romance",
  "Misterio",
  "Suspenso",
  "Thriller",
  "Ciencia ficción",
  "Fantasía",
  "Horror",
  "Terror",
  "Aventura",
  "Histórica",
  "Biografía",
  "Autobiografía",
  "Poesía",
  "Drama",
  "Comedia",
  "Juvenil",
  "Infantil",
  "Autoayuda",
  "Negocios",
  "Cocina",
  "Arte",
  "Viajes",
  "Religión",
  "Filosofía",
  "Ciencia",
  "Tecnología",
  "Política",
  "Historia",
  "Psicología",
  "Sociología",
  "Educación",
  "Deportes",
  "Música",
  "Cine",
  "Cómics",
  "Manga",
  "Literatura clásica",
  "Literatura contemporánea",
  "Distopía",
  "Realismo mágico",
  "Ensayo",
  "Crónica",
  "Novela gráfica",
  "Novela negra",
  "Erótica",
  "Paranormal",
  "Épica",
  "Fábula",
  "Sátira",
  "Westerns",
  "Ecología",
  "Matemáticas",
  "Medicina",
  "Derecho",
  "Economía",
  "Arquitectura",
  "Fotografía",
  "Diseño",
  "Humor",
  "Antología",
] as const;

export type BookGenre = typeof BOOK_GENRES[number];
